### PR TITLE
more fixes for environment variables, for non-standard installations

### PR DESCRIPTION
**Pull request by ApplySci**
Similar to last PR, three fixes to use environmental variables; this is crucial for non-standard installations that change the default ports.

By the way, should I be submitting against PNTN-12-user-management-integration or master? It looks like you've got some big changes in progress in the PNTN-12 branch!

### CODE REVIEW

**Comment by ctizen** [comment]
Thanks!

I think these changes are OK to go into master; PNTN-12 is a really huge integration branch, but I'd like not to have any unrelated changes inside it :) But yes, it might be required to check it for similar things once again when it's ready.

**Comment by ctizen** [comment]
Oh. I just realized that fixes in Makefile are not really correct, because `make empty_event` is executed outside of docker environment. We should have left is as is, or rewrite it to use `docker exec`.

**Comment by ctizen** [comment]
@ApplySci I'm gonna fix it later, or you can do it yourself, if you have time to.

**Comment by ApplySci** [comment]
I'm only using pantheon *outside* docker, so this fix works (and is useful) for me. I don't know how to do that `docker exec` stuff.

**Pull request merged**
