### PR TITLE
Fix german translations for Rheda

### PR DESCRIPTION
**Pull request by Jesterboxboy**
I completed the german translation file and also added some corrections as german is my native language. The edit was done via poedit and the mo file is already compiled.

### CODE REVIEW

**Comment by ctizen** [comment]
@Jesterboxboy thank you so much!
Please note that the translation will be applied to current master branch, which contains pantheon v2.0. If you still use v1.x and you'd want to update the translation for that version, please make PR to `pantheonv1-maintenance` branch.

I would also very appreciate Tyr translation to german, is there any chance you could take a look on it? :)

**Comment by ctizen** [comment]
Translations have been deployed to our developer-supported pantheon instance (https://r.riichi.top).

**Comment by Jesterboxboy** [comment]
@ctizen Yes i will also do the translation for Tyr. Creating a new po file from the messages.pot equivalent to ru.po is enough?
I don't see any compiled mo file in the app/i18n folder, is this done at runtime somehow?

**Comment by ctizen** [comment]
@Jesterboxboy yep, it's compiled into json files for mobile SPA, so .mo files are not required at all here. Just use `messages.pot` file as a template for your translation.

New translation should be added both to the build pipeline (here: https://github.com/MahjongPantheon/pantheon/blob/master/Tyr/Makefile#L35) and to the interface (here and further: https://github.com/MahjongPantheon/pantheon/blob/master/Tyr/app/services/i18n.ts#L5). 
After that, json translation files should be rebuilt with `make i18n_compile` in project folder or `make i18n_update` in Tyr folder. AFAIR, this should be enough.

If you don't feel like digging into frontend code, just send me .po file :) I'll do all other things.

**Comment by Jesterboxboy** [comment]
@ctizen 
Thanks for the information. I spent the last week setting up the new version to test it out in our club. 
I will most likely do the german translation for Tyr during the next 2-3 weeks after we played a few games with it, and i also need to rework the translation for Rheda i noticed, quite a few things that are still unpolished.

**Pull request merged**
